import { Field } from './Field.jsx';
import { PEER_SCHOOLS } from '../../lib/peerLogos.js';

const RESEARCH_PILLARS = [
  {
    title: 'Self-Regulated Learning',
    body: 'When students have the right information, they can set meaningful goals, monitor their progress, and reflect on what’s working — adapting and driving their own learning.',
    items: [
      'Students see their progress, performance, and priorities at a glance',
      'Progress updates create a feedback loop students use to adjust and improve',
      'A clear view of the whole journey helps students set goals and take ownership',
    ],
  },
  {
    title: 'Behavioral Economics',
    body: 'When next steps are clear, timely, and easy to act on, students are more likely to follow through and build momentum toward success.',
    items: [
      'Clear visual cues make priorities and next steps easy to follow',
      'Timely nudges prompt action before students fall behind',
      'Celebrations and success signals reinforce momentum and persistence',
    ],
  },
  {
    title: 'Social Presence',
    body: 'When students feel seen, connected, and supported, they are more likely to engage, participate, and persist.',
    items: [
      'Personalized outreach helps students feel seen and valued',
      'Students can feel the class moving around them — and know they’re not alone',
      'Teachers can reach the right student at the right moment — before silence turns into withdrawal',
    ],
  },
];

const GAP_ROWS = [
  {
    who: 'The student sees…',
    body: 'a gray wall of text. The signals they need — success, direction, progress — are buried. A slipping student can quietly fade, and nothing pulls them back.',
  },
  {
    who: 'The parent wants…',
    body: 'to be the cheerleader and coach their kid needs, but Canvas gives opaque data without a story they can act on.',
  },
  {
    who: 'The teacher faces…',
    body: 'hours of slow manual work to find and reach at-risk students, one student at a time. Paid for in lost evenings.',
  },
];

const IN_THEIR_WORDS = [
  {
    text: 'The enthusiasm generated by Delphinium has translated into increased engagement and work completion.',
    attr: 'Instructional Coach',
  },
  {
    text: 'We have had students redo a quiz that they did poorly on to earn more points so they could just earn googly eyes for their avatar!',
    attr: 'Online Teacher',
  },
  {
    text: '[Delphinium has] given me so much more opportunity to work one-on-one with my students. That’s why I went into teaching! This has saved most of my Saturday nights!',
    attr: 'Math Teacher',
  },
];

const VIDEOS = [
  {
    title: 'Digital Learning & Curriculum Directors',
    href: 'https://www.youtube.com/watch?v=Tp3IO0TzvM0',
  },
  {
    title: 'Teachers & Instructional Coaches',
    href: 'https://www.youtube.com/watch?v=3N0SXpFT36w',
  },
];

export default function ExecutiveSummarySection({
  fields,
  quote,
  highlightFields,
  pageLabel = '· The case for engagement',
  pageLabelB = '· Why it pays off',
  pageLabelC = '· Why it pays / trust',
}) {
  const hl = highlightFields;
  const painPoints = [fields.PAIN_POINT_1, fields.PAIN_POINT_2, fields.PAIN_POINT_3];

  return (
    <>
      {/* Page A — The case for engagement */}
      <section className="sheet exec-framing">
        <div className="page-label screen-only">{pageLabel}</div>
        <div className="doc-kicker">Executive summary</div>
        <h2 className="doc-h2 exec-framing-title">Education moved online. Engagement didn&apos;t follow.</h2>

        <p className="exec-framing-body">
          More education has moved online &mdash; and students and families expect that access now. But
          delivering content online is not the same as engaging students. In a classroom, teachers can read
          the room, catch a glance, stand by a student who is drifting, or capture focus with a quick activity.
          None of that survives the move to a screen. Engagement has been waiting for online tools to catch up.
        </p>

        <blockquote className="exec-framing-quote">
          <p className="exec-framing-quote-tx">
            &ldquo;There&apos;s downsides to Canvas, if you ask kids, they don&apos;t like Canvas. It&apos;s
            basic, it needs something else to engage in the way we&apos;re looking for. Canvas itself falls
            way short.&rdquo;
          </p>
          <div className="exec-framing-quote-by">&mdash; Ryan Hansen, Digital Learning Director</div>
        </blockquote>

        <div className="keep exec-framing-block">
          <div className="exec-framing-label">When engagement breaks down&hellip;</div>
          <div className="exec-stat-trio">
            <div className="exec-stat-trio-card">
              <div className="exec-stat-trio-label">Attendance</div>
              <div className="exec-stat-trio-num">1 in 4</div>
              <div className="exec-stat-trio-body">students are chronically absent &mdash; still elevated years after the shift online.</div>
              <div className="exec-stat-trio-src">RAND / Return to Learn Tracker, 2024&ndash;25</div>
            </div>
            <div className="exec-stat-trio-card">
              <div className="exec-stat-trio-label">Achievement</div>
              <div className="exec-stat-trio-num">1 in 3</div>
              <div className="exec-stat-trio-body">students score below grade level across all core subjects &mdash; below pre-pandemic levels.</div>
              <div className="exec-stat-trio-src">The Nation&apos;s Report Card (NAEP), 2024</div>
            </div>
            <div className="exec-stat-trio-card">
              <div className="exec-stat-trio-label">Cost</div>
              <div className="exec-stat-trio-num">$229K</div>
              <div className="exec-stat-trio-body">the average cost of a K&ndash;12 education, and a student&apos;s lost potential, when they don&apos;t finish.</div>
              <div className="exec-stat-trio-src">U.S. Census Bureau, FY2024</div>
            </div>
          </div>
        </div>

        <p className="exec-framing-body">
          These aren&apos;t three separate crises. They share one common driver: <b>disengagement</b>. When
          students aren&apos;t engaged, the conditions for learning &mdash; and for finishing &mdash; quietly
          disappear.
        </p>

        <div className="keep doc-panel-indigo exec-thesis">
          <p className="exec-framing-body" style={{ margin: 0 }}>
            <b>Everything moved online except the part that matters most.</b>
            {' '}
            Your school has strong curriculum, capable teachers, and a platform to deliver it all. But great
            teaching was never really about content &mdash; it&apos;s about knowing when a student is winning
            and when they&apos;re slipping, and making sure they feel seen and feel progress along the way. The
            tools built for online learning were designed to deliver content, not to spark engagement with it.
            That signal, that connection &mdash; that&apos;s what&apos;s been missing.
          </p>
        </div>

        <div className="keep exec-framing-block">
          <div className="exec-framing-label">Canvas is data-rich, but insight-poor.</div>
          <p className="exec-framing-body exec-framing-body--tight">
            Canvas captures a lot of information &mdash; Assignments, Gradebook, Syllabus, Modules, Analytics,
            etc. But it is scattered across pages built for storage, not engagement.
          </p>
          <div className="exec-gap">
            {GAP_ROWS.map(row => (
              <div key={row.who} className="exec-gap-row">
                <div className="exec-gap-who">{row.who}</div>
                <div className="exec-gap-tx">{row.body}</div>
              </div>
            ))}
          </div>
        </div>

        <div className="keep exec-framing-block">
          <div className="exec-framing-label">Specifically at your school</div>
          <p className="exec-framing-body exec-framing-body--tight">
            At
            {' '}
            <Field value={fields.SCHOOL_NAME} highlight={hl} />
            , you&apos;re working to solve
            {' '}
            <Field value={fields.PRIMARY_PAIN} highlight={hl} />
            , and a few specific pressures sit underneath it:
          </p>
          <div className="doc-pain-list exec-framing-pain-list">
            {painPoints.map(point => (
              <div key={point} className="doc-pain-item exec-framing-pain-item">
                <span className="doc-pain-arrow">&rarr;</span>
                <div className="doc-pain-text">
                  <Field value={point} highlight={hl} />
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="keep exec-framing-cost">
          <b>What you need is the tools to turn that data into action &mdash; Delphinium.</b>
        </div>
      </section>

      {/* Page B — Why it pays off */}
      <section className="sheet exec-framing">
        <div className="page-label screen-only">{pageLabelB}</div>
        <div className="doc-kicker">Executive summary</div>
        <h2 className="doc-h2 exec-framing-title">Canvas delivers content. Delphinium delivers engagement.</h2>

        <p className="exec-framing-body">
          For an online student, Canvas is the entire school experience. Delphinium adds a quick layer over
          your existing Canvas courses &mdash; no rebuild, no new platform. It re-engages students, gives
          parents a clear picture, and hands teachers early warnings instead of spreadsheets.
        </p>

        <div className="keep exec-framing-block">
          <div className="exec-framing-label">Proof it works</div>
          <div className="exec-proof-bento">
            <div className="exec-proof-stat">
              <div className="exec-framing-stat-num">31%</div>
              <div className="exec-framing-stat-label">fewer failures</div>
              <div className="exec-framing-stat-src">across 72 classes and 6,000+ students &middot; Davis Connect case study, 2022 vs. 2023</div>
            </div>
            <div className="exec-bar-chart">
              <div className="exec-bar-chart-title">Course failure rate &mdash; Davis Connect</div>
              <div className="exec-bar-row">
                <div className="exec-bar-label">Without Delphinium</div>
                <div className="exec-bar-track"><div className="exec-bar-fill exec-bar-fill--gray" style={{ width: '100%' }} /></div>
                <div className="exec-bar-value">26%</div>
              </div>
              <div className="exec-bar-row">
                <div className="exec-bar-label">With Delphinium</div>
                <div className="exec-bar-track"><div className="exec-bar-fill exec-bar-fill--green" style={{ width: '69%' }} /></div>
                <div className="exec-bar-value">18%</div>
              </div>
            </div>
            <div className="exec-proof-stat">
              <div className="exec-framing-stat-num">72%</div>
              <div className="exec-framing-stat-label">say more motivating</div>
              <div className="exec-framing-stat-src">of students say Delphinium is more or much more motivating than a traditional course</div>
            </div>
          </div>
          <p className="exec-framing-body exec-framing-body--tight">
            Delphinium is built on 14 years of published research. The results are measured, not promised. The
            courses didn&apos;t change. The teachers didn&apos;t change. Engagement did &mdash; and so did the
            outcomes.
          </p>
          <p className="exec-framing-body exec-framing-body--tight">
            In our research, when we ask students how a Delphinium course is different from a traditional
            course, one of the most common words we hear back is &ldquo;Fun.&rdquo; They also report doing
            their work earlier &mdash; and with higher quality. One student put it this way: &ldquo;I was
            sitting on the couch watching Netflix and the thought popped into my head &mdash; I could be doing
            homework right now &mdash; and I did!&rdquo; That is intrinsic motivation &mdash; not a reminder,
            not a deadline, but a student who wants to engage. That is what Delphinium was built to create
            &mdash; and the data proves it works.
          </p>
        </div>

        <div className="keep exec-framing-block">
          <div className="exec-framing-label">Why it works &mdash; the research behind the design</div>
          <div className="exec-framing-pillars exec-framing-pillars--wide">
            {RESEARCH_PILLARS.map(({ title, body, items }) => (
              <div key={title} className="exec-framing-pillar">
                <div className="exec-framing-pillar-title">{title}</div>
                <div className="exec-framing-pillar-body">{body}</div>
                <div className="exec-framing-pillar-sub">In Delphinium:</div>
                <ul className="exec-framing-pillar-list">
                  {items.map(item => <li key={item}>{item}</li>)}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Page C — Why it pays / trust */}
      <section className="sheet exec-framing">
        <div className="page-label screen-only">{pageLabelC}</div>
        <div className="doc-kicker">Executive summary</div>
        <h2 className="doc-h2 exec-framing-title">Your school already runs on Canvas &mdash; make it work harder for you!</h2>

        <div className="exec-mult-flow">
          <div className="exec-mult-step">
            <div className="exec-mult-step-label">Start with what you have&hellip;</div>
            <div className="exec-mult-step-body">Great teachers, curriculum, and tools</div>
          </div>
          <div className="exec-mult-arrow">&rarr;</div>
          <div className="exec-mult-step exec-mult-step--accent">
            <div className="exec-mult-step-label">Multiply by Delphinium&hellip;</div>
            <div className="exec-mult-step-body">Engagement and early warnings, layered over your Canvas; students connect, build momentum, and drive their learning</div>
          </div>
          <div className="exec-mult-arrow">&rarr;</div>
          <div className="exec-mult-step">
            <div className="exec-mult-step-label">And you get&hellip;</div>
            <div className="exec-mult-step-body">Students who see their whole path and own it &middot; families armed to encourage and coach &middot; teachers who reach the right student at the right time</div>
          </div>
          <div className="exec-mult-arrow">&rarr;</div>
          <div className="exec-mult-step exec-mult-step--outcome">
            <div className="exec-mult-step-label">Better outcomes for everyone</div>
            <div className="exec-mult-step-body">More students succeed the first time; attendance, completion, and retention rise; families feel connected and confident; teachers do more in less time, with less frustration!</div>
          </div>
        </div>

        <p className="exec-framing-body">
          Results like a 31% drop in failures means more of the ~$229K invested in each student actually
          reaches the finish line &mdash; the same budget, working harder, every year.
          {' '}
          <b>Doing nothing is the most expensive option on the table.</b>
        </p>

        <div className="keep exec-framing-block">
          <div className="exec-framing-label">In their words&hellip;</div>
          <div className="exec-words-grid">
            {IN_THEIR_WORDS.map(({ text, attr }) => (
              <blockquote key={attr} className="exec-framing-quote exec-framing-quote--compact">
                <p className="exec-framing-quote-tx">&ldquo;{text}&rdquo;</p>
                <div className="exec-framing-quote-by">&mdash; {attr}</div>
              </blockquote>
            ))}
          </div>
        </div>

        <div className="keep doc-panel-indigo exec-clients">
          <div className="exec-clients-eye">Over 125,000 Delphinium enrollments this year</div>
          <div className="exec-clients-sub">The investment in engagement has already paid off, at scale, in schools like yours!</div>
          <div className="peer-logos-row" role="list">
            {PEER_SCHOOLS.map(({ name, logo }) => (
              <figure key={name} className="peer-logo" role="listitem">
                <img src={logo} alt={name} loading="lazy" />
              </figure>
            ))}
          </div>
        </div>

        <div className="keep exec-framing-block">
          <div className="exec-framing-label">Hear the full story&hellip;</div>
          <p className="exec-framing-body exec-framing-body--tight">
            Meet the educators who use Delphinium every day to drive better outcomes for their students.
          </p>
          <div className="exec-videos-grid">
            {VIDEOS.map(({ title, href }) => (
              <a key={title} className="exec-video-card" href={href} target="_blank" rel="noopener noreferrer">
                <span className="exec-video-play">&#9654;</span>
                <span className="exec-video-tx">
                  <span className="exec-video-eyebrow">Watch video</span>
                  <span className="exec-video-title">{title}</span>
                </span>
              </a>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
